// src/utils/permissions.js

// Definición de todos los permisos del sistema
export const PERMISSIONS = {
  // Usuarios
  VER_USUARIO: 'VER_USUARIO',
  CREAR_USUARIO: 'CREAR_USUARIO',
  MODIFICAR_USUARIO: 'MODIFICAR_USUARIO',
  ELIMINAR_USUARIO: 'ELIMINAR_USUARIO',

  // Roles
  VER_ROL: 'VER_ROL',
  CREAR_ROL: 'CREAR_ROL',
  MODIFICAR_ROL: 'MODIFICAR_ROL',
  ELIMINAR_ROL: 'ELIMINAR_ROL',

  // Permisos
  VER_PERMISO: 'VER_PERMISO',
  CREAR_PERMISO: 'CREAR_PERMISO',
  MODIFICAR_PERMISO: 'MODIFICAR_PERMISO',
  ELIMINAR_PERMISO: 'ELIMINAR_PERMISO',

  // Auditoría
  VER_AUDITORIA: 'VER_AUDITORIA',

  // Gestión Académica
  VER_DOCENTE: 'VER_DOCENTE',
  CREAR_DOCENTE: 'CREAR_DOCENTE',
  MODIFICAR_DOCENTE: 'MODIFICAR_DOCENTE',
  ELIMINAR_DOCENTE: 'ELIMINAR_DOCENTE',

  VER_CARRERA: 'VER_CARRERA',
  CREAR_CARRERA: 'CREAR_CARRERA',
  MODIFICAR_CARRERA: 'MODIFICAR_CARRERA',
  ELIMINAR_CARRERA: 'ELIMINAR_CARRERA',

  VER_MATERIA: 'VER_MATERIA',
  CREAR_MATERIA: 'CREAR_MATERIA',
  MODIFICAR_MATERIA: 'MODIFICAR_MATERIA',
  ELIMINAR_MATERIA: 'ELIMINAR_MATERIA',

  VER_GRUPO: 'VER_GRUPO',
  CREAR_GRUPO: 'CREAR_GRUPO',
  MODIFICAR_GRUPO: 'MODIFICAR_GRUPO',
  ELIMINAR_GRUPO: 'ELIMINAR_GRUPO',

  VER_PERIODO: 'VER_PERIODO',
  CREAR_PERIODO: 'CREAR_PERIODO',
  MODIFICAR_PERIODO: 'MODIFICAR_PERIODO',
  ELIMINAR_PERIODO: 'ELIMINAR_PERIODO',

  VER_GESTION: 'VER_GESTION',
  CREAR_GESTION: 'CREAR_GESTION',
  MODIFICAR_GESTION: 'MODIFICAR_GESTION',
  ELIMINAR_GESTION: 'ELIMINAR_GESTION',

  VER_AULA: 'VER_AULA',
  CREAR_AULA: 'CREAR_AULA',
  MODIFICAR_AULA: 'MODIFICAR_AULA',
  ELIMINAR_AULA: 'ELIMINAR_AULA',

  // Horarios
  VER_HORARIO: 'VER_HORARIO',
  CREAR_HORARIO: 'CREAR_HORARIO',
  MODIFICAR_HORARIO: 'MODIFICAR_HORARIO',
  ELIMINAR_HORARIO: 'ELIMINAR_HORARIO',

  // Reportes
  VER_REPORTE: 'VER_REPORTE',
  GENERAR_REPORTE: 'GENERAR_REPORTE',

  // Asistencia
  VER_ASISTENCIA: 'VER_ASISTENCIA',
  REGISTRAR_ASISTENCIA: 'REGISTRAR_ASISTENCIA',
  MODIFICAR_ASISTENCIA: 'MODIFICAR_ASISTENCIA'
};

// Helper para verificar permisos
export const checkPermission = (userPermissions, requiredPermission) => {
  return userPermissions && userPermissions.includes(requiredPermission);
};